### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by bunyodkamalov**

### CODE REVIEW

**Review by FirdavsAsadov — COMMENTED** [review]
Xato feature/#33 ga tashlayabsiz siz devga tashlashingiz kerak

**Review by FirdavsAsadov — CHANGES_REQUESTED** [review]
xato branchni tog'irlang o'zizni branchizdan devga tashlang :)

**Review by Jasurbek1223 — CHANGES_REQUESTED** [review]
BRANCH qaytadan tog'irlab yozing va oziznikidan devga jonating

**Review by azam-amonov — CHANGES_REQUESTED** [review]
Check branch

**Pull request closed without merging**
